### ISSUE TITLE
Activate scene as action?

### ISSUE THREAD

**Issue by tobbensoft** [nickneos/Appdaemon-ZHA-Hue-Dimmer-Switch#1]
Hi 

Thanks for a nice "feature" everything works as intended but I'm missing the option to call a service to turn on a scene for instance..

Is that possible to implement?

:)

**Comment by nickneos** [comment]
Try it with an advanced config. I don't have a scene to test but I think it should work

eg.
```yaml
dimmer_main:
  module: zha_hue_dimmer_switch
  class: HueDimmerSwitch
  switch: '00:00:00:00:00:00:00:00'
  advanced:
    on_short_release: 
      action_type: turn_on
      entity: scene.scene1
    up_short_release: 
      action_type: turn_on
      entity: scene.scene2
    down_short_release: 
      action_type: turn_on
      entity: scene.scene3
    off_short_release: 
      action_type: turn_on
      entity: scene.scene4
```
